#!/bin/sh

[ "$_" == "$0" ]\
 && echo "Do not run ${0} directly, it must be sourced from another script!

USAGE:
. ${0}
source ${0}
"

# If no SSH agent is already running, start one now. Re-use sockets so we never
# have to start more than one session.
export SSH_AUTH_SOCK="${HOME}/.ssh-socket"
SSH_AGENT_TMPFILE="$(mktemp)"
SSH_AGENT_PIDFILE="${HOME}/.ssh-agent-pid"

# test
ssh-add -l >/dev/null 2>&1

if [ $? = 2 ]; then
 # No ssh-agent running

  rm -f "${SSH_AUTH_SOCK}"

 # >| allows output redirection to over-write files if no clobber is set

  ssh-agent -a "${SSH_AUTH_SOCK}" >| "${SSH_AGENT_TMPFILE}"
  source "${SSH_AGENT_TMPFILE}"

  echo ${SSH_AGENT_PID} >| "${SSH_AGENT_PIDFILE}"

  ssh-add ~/.ssh/id_rsa

fi

rm "${SSH_AGENT_TMPFILE}"
