#!/bin/sh

readonly TEXT=${*:-$(case $(( $RANDOM % 5 )) in
 '0' ) run-in-container sensors --no-adapter;;
 '1' ) run-in-container fortune;;
 '2' ) echo 'This system is running since' ;uptime --since;;
 '3' ) echo 'This system is ' ;uptime --pretty;;
 '4' ) uname -a;;
 '5' ) echo 'I am '; whoami;;
 * ) echo "Error in _textselect. Nothing is selected!";;
esac
)}

case "$(( $RANDOM % 2 ))" in
 '0' ) PODMAN_RUN_ARGS="-it --rm -e TERM=${TERM}" exec run-in-container docker.io/mpepping/ponysay:latest "$TEXT";;
 '1' ) ACTION=( /cowsay/bin/cowsay /cowsay/bin/cowthink );
       MODE=( -b -d -g -p -s -t -w -y );
       exec container-build-run - "${ACTION[RANDOM%${#ACTION[@]}]}" -W 77 "${MODE[RANDOM%${#MODE[@]}]}" "${TEXT}" << Containerfile

# containerfile-build-run directives
# IMAGE_NAME=cowsay:latest
# START_ARGUMENTS=-i --rm -e TERM=${TERM}
# SKIP_TESTS=true

FROM docker.io/library/alpine:edge AS base
RUN apk add --update --no-cache perl

FROM base AS prepare

RUN apk add git
RUN git clone https://github.com/tnalpgge/rank-amateur-cowsay.git /cowsay-repo
RUN mkdir -vp /cowsay\
 && cd /cowsay-repo\
 && ./install.sh /cowsay

RUN rm -rvf /cowsay/man

FROM base

COPY --from=prepare /cowsay /cowsay
CMD [ "/cowsay/bin/cowsay" ]
Containerfile
;;
esac