#!/bin/sh

TEXT=$*
TEXTSELECT=(
 "$(run-in-container sensors --no-adapter | sed -e 's/(.*//')"
 "$(run-in-container fortune)"
 "$(echo 'This system is running since' ;uptime --since)"
 "$(echo 'This system is ' ;uptime --pretty)"
 "$(uname -a)"
 "$(echo 'I am '; whoami)"
 )
[ "$1" == "" ] && TEXT=${TEXTSELECT[RANDOM%${#TEXTSELECT[@]}]}


PODMAN_RUN_ARGS="-it --rm -e TERM=${TERM}"\
 exec run-in-container docker.io/mpepping/ponysay:latest "$TEXT"
read -n 1 -s
